# Generated by Django 4.2.6 on 2023-11-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="email_code",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Проверочный код"
            ),
        ),
    ]
