# Generated by Django 4.2.6 on 2023-10-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=500, verbose_name='слаг')),
                ('text', models.TextField(verbose_name='текст')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(verbose_name='флаг публикации')),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
