# Generated by Django 4.2.6 on 2023-11-10 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_version", models.IntegerField(verbose_name="номер версии")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="название"
                    ),
                ),
                ("is_current", models.BooleanField(verbose_name="текущая версия")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия",
                "verbose_name_plural": "версии",
            },
        ),
    ]
