# Generated by Django 4.2.6 on 2023-11-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="опубликовано"),
        ),
    ]
